### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by luna-duclos** [techknowlogick/gitea-buildkite-connector#6]
I'd like to potentially use this, but I can't find any license under which it is allowed to be used.
Would it be possible to add one ?

**Comment by techknowlogick** [comment]
Hey @luna-duclos it is licensed under MIT, let me add that to the repo now. Although you may wish to look into a more full-fledged project at https://deanpcmad.com/2023/buildtea/

**Comment by luna-duclos** [comment]
Thank you <3 <3
